xml_path: ../assets/b2/scene.xml

train:
  total_timesteps: 2500000
  n_steps: 2048
  batch_size: 256
  learning_rate: 0.0002
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.004
  vf_coef: 0.6

env:
  target_lin_vel: 0.22
  max_episode_steps: 2200
  frame_skip: 4
  action_scale: 0.20
  target_delta_scale: 0.32
  kp: 60.0
  kd: 2.2
  standup_steps: 80
  standup_gain: 0.4
  fall_height_threshold: 0.20
  ctrl_penalty_weight: 0.0018
  smooth_penalty_weight: 0.0018
  orient_penalty_weight: 0.9
  stand_pose_penalty_weight: 0.35
  alive_bonus: 1.0
  reset_noise_qpos: 0.0003
